name: CytoCluster Build

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run pytest
        run: poetry run python -m pytest --import-mode=append cytocluster/tests/ --cov=cytocluster/tests

      - name: Run Coverage
        run: poetry run python -m coverage report -m;

      - name: Generate XML Report
        run: poetry run python -m coverage xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0